local_repository(
    name = "rules_multi_tsc",
    path = "../rules",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

new_local_repository(
    name="node_modules_archive",
    path=".",
    build_file_content="""
exports_files([
    "node_modules/typescript/lib/tsc.js",
    "node_modules/rollup/bin/rollup",
    "node_modules/uglify-es/bin/uglifyjs",
])

filegroup(
    name = "default_typings",
    srcs = glob([
        "node_modules/@types/**",
    ]),
    visibility = ["//visibility:public"],
)

filegroup(name = "long", srcs = glob(["node_modules/long/**/*",]), visibility = ["//visibility:public"])
filegroup(name = "bson", srcs = glob(["node_modules/bson/**/*",]), visibility = ["//visibility:public"])
filegroup(name = "buffer", srcs = glob(["node_modules/buffer/**/*",]), visibility = ["//visibility:public"])

filegroup(
    name = "rollup_plugins",
    srcs = glob([
        "node_modules/rollup-plugin-commonjs/**/*",
        "node_modules/rollup-plugin-node-resolve/**/*",
        "node_modules/rollup-plugin-alias/**/*",
        "node_modules/rollup-plugin-includepaths/**/*",
    ]),
    visibility = ["//visibility:public"],
)
"""
)

http_archive(
    name = "node",
    url = "https://nodejs.org/dist/v10.14.2/node-v10.14.2-darwin-x64.tar.gz",
    strip_prefix = "node-v10.14.2-darwin-x64",
    build_file_content="""
exports_files([
    "bin/node",
])
"""
)
